config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    get "/blog/post/new", to: "blog_posts#new", as: :new_blog_post
    get "/blog/post/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
    patch "/blog/post/:id/update", to: "blog_posts#update", as: :update_blog_post
    get "/blog/post/:id", to: "blog_posts#show", as: :blog_post
    post "/blog/post/create", to: "blog_posts#create", as: :blog_posts
    delete "/blog/post/:id/delete", to: "blog_posts#destroy", as: :delete_blog_post
    root "blog_posts#index", as: :blog_post_home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable, :lockable, :timeoutable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
# frozen_string_literal: true

class BlogPostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

    def index
        @posts = BlogPost.all
    end

    def show
        @post = BlogPost.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end

    def new
        @post = BlogPost.new
    end

    def create
        @post = BlogPost.new(blog_post_params)
        if @post.save
            redirect_to :index
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @post = BlogPost.find(params[:id])
    end

    def update
        @post = BlogPost.find(params[:id])
        if @post.update(blog_post_params)
            redirect_to root_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @post = BlogPost.find(params[:id])
        if @post.destroy
            redirect_to root_path
        else
            render :edit
        end
    end

    private

    def blog_post_params
        params.require(:blog_post).permit(:title, :body)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <%= form.button %>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= form_with model: @post, url: { action: "update" } do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <%= form.button %>
<% end %>

<%= button_to "Delete", { :controller => :blog_posts, :action => 'destroy', :id => @post.id }, :method => :delete %>

app/views/blog_posts/index.html.erb
<% @posts.each do |post| %>
  <div>
    <h2><%= link_to post.title, post%></h2>
    <%= post.body %>
  </div>
<% end %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render partial: "form", locals: {post: @post}%>

app/views/blog_posts/show.html.erb
<%= link_to "Edit", edit_blog_post_path %>
<%= button_to "Delete", { :controller => :blog_posts, :action => 'destroy', :id => @post.id }, :method => :delete %>
<h1><%= @post.title  %></h1>
<%= @post.body %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="antialiased text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900">
<div class="sticky top-0 z-40 w-full backdrop-blur flex-none transition-colors duration-500 lg:z-50 lg:border-b lg:border-slate-900/10 dark:border-slate-50/[0.06] bg-white/95 supports-backdrop-blur:bg-white/60 dark:bg-transparent">
  <div class="max-w-8xl mx-auto">
    <div class="py-4 border-b border-slate-900/10 lg:px-8 lg:border-0 dark:border-slate-300/10 px-4">
      <div class="relative flex items-center">
        <div class="relative hidden lg:flex items-center ml-auto">
          <nav class="text-sm leading-6 font-semibold text-slate-700 dark:text-slate-200">
            <ul class="flex space-x-8">
              <li>
                <%= link_to "Home", blog_post_home_path, class: "hover:text-sky-500 dark:hover:text-sky-400" %>
              </li>
              <% if user_signed_in? %>
                <li>
                  <%= link_to "Profile", edit_user_registration_path, class: "hover:text-sky-500 dark:hover:text-sky-400" %>
                </li>
                <li>
                  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "hover:text-sky-500 dark:hover:text-sky-400" %>
                </li>
                <li>
                  <%= link_to "New Blog Post", new_blog_post_path, class: "hover:text-sky-500 dark:hover:text-sky-400" %>
                </li>
              <% else %>
                <li>
                  <%= link_to "Login", new_user_session_path, class: "hover:text-sky-500 dark:hover:text-sky-400" %>
                </li>
                <li>
                  <%= link_to "Sign Up", new_user_registration_path, class: "hover:text-sky-500 dark:hover:text-sky-400" %>
                </li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>